import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased bg-gray-50">
        {/* Navbar kodi shu yerda turadi */}
        <nav className="fixed top-0 w-full z-50 border-b bg-white/95 backdrop-blur-md shadow-sm">
          {/* ... siz yozgan Navbar ichki kodi ... */}
        </nav>

        {/* Sahifa mazmuni Navbar ostida qolib ketmasligi uchun padding (pt-24) beramiz */}
        <main className="pt-24 container mx-auto px-4">
          {children}
        </main>
      </body>
    </html>
  );
}
